### PR TITLE
Doesn't build on linux

### PR DESCRIPTION
**Pull request by mk0x9**
Renamed and updated references to src/link.ts. Now package builds on my linux machine.

### CODE REVIEW

**Comment by mk0x9** [comment]
Here's the build log before changes:

```
$ npm run build

> react-mvx@2.0.0-rc900 build /home/mk9/code/React-MVx
> npm run pull && npm run compile


> react-mvx@2.0.0-rc900 pull /home/mk9/code/React-MVx
> git submodule update --remote && cp ./submodules/NestedLink/tags.* . && cp ./submodules/NestedLink/src/* ./src/valuelink


> react-mvx@2.0.0-rc900 compile /home/mk9/code/React-MVx
> tsc && ./node_modules/.bin/rollup --config

src/index.ts(4,18): error TS2307: Cannot find module './link'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-mvx@2.0.0-rc900 compile: `tsc && ./node_modules/.bin/rollup --config`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-mvx@2.0.0-rc900 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Bolik** [comment]
+1

**Comment by gaperton** [comment]
Thanks.

**Comment by gaperton** [comment]
For the future - we commit build results as well. Next time, please do `npm run build` before commit.

**Pull request merged**
